DROP TABLE  IF EXISTS NCAA_STATS;

CREATE TABLE NCAA_STATS  (
    YEAR INT NOT NULL,
    RANK INT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    RATING DOUBLE NOT NULL,
    WIN INT NOT NULL,
    LOSS INT NOT NULL,
    SCHEDL DOUBLE NOT NULL,
    SCHEDL_RANK INT  NOT NULL,
    WIN_TOP_25 INT  NOT NULL,
    LOSS_TOP_25 INT  NOT NULL,
    WIN_TOP_50 INT NOT NULL,
    LOSS_TOP_50 INT  NOT NULL,
    PREDICTOR DOUBLE NOT NULL,
    PREDICTOR_RANK INT NOT NULL,
    GOLDEN_MEAN DOUBLE  NOT NULL,
    GOLDEN_MEAN_RANK INT NOT NULL,
    RECENT DOUBLE NOT NULL,
    RECENT_RANK INT NOT NULL
);

